### ISSUE TITLE
Assembly still doesnt have strong name

### ISSUE THREAD

**Issue by FixRM** [StefanKert/azuredevops-codesigning-task#10]
Hello @StefanKert,

First of all, thank you for your tool! Can you please help me to understand the problem? Tool says my DLL was successfully signed but VS still telling me it's not. :(

Pipeline is: Build -> Sign -> NuGet Pack -> NuGet Publish -> Use as NuGet in other solution.

According to logs Sign and NuGet pack use the same assembly path

**Comment by StefanKert** [comment]
Hi @FixRM,

I am afraid to tell you that this is only for Codesigning (certificate based). The extension does not (at least not yet) support strong named assemblies. I actually don´t know if it makes sense to support this case because there are already ways to do this automatically like [delay signing](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/t07a3dye(v=vs.100)).

**Comment by FixRM** [comment]
Thanks for your answer. Now I understand the difference. I believe it still make sense as delay signing still require sp.exe tool as well as Pfx certificate. It would be much easier to have task then dealing with cli manually

**Comment by StefanKert** [comment]
I totally agree with you. Do you think this is something that should be included in this extension? I am not 100% sure because code signing to me is different from strong key signing, but glad to hear your opinion on this :)

**Comment by FixRM** [comment]
@StefanKert, I believe it should additional task. At the moment I still don't understand the best way to solve problem. Delay signing is a nightmare! Nobody here should make contributors to deal with it :)

The ideal looks simple: take weak named assembly and make it strong named during CI build. I found that Newtonsoft.Json use some dotnet cli tooling for this:
`dotnet tool install --tool-path . SignClient`
but process looks complicated :(

**Comment by FixRM** [comment]
@StefanKert. It looks like I found the way out. I can use [conditional configuration](https://blogs.msdn.microsoft.com/mcsuksoldev/2013/05/23/unit-testing-delay-signed-assemblies-on-the-hosted-tfs-build-service/) and [.snk key file (instead of password protected .pfx)](https://www.karpach.com/visual-studio-team-services-assembly-signing.htm) to build signed assembly on hosted agent.

Anyway thank you for your time!
