### ISSUE TITLE
Allow certificates to be appended

### ISSUE THREAD

**Issue by amura11** [StefanKert/azuredevops-codesigning-task#19]
One of the options for the SignTool application is `/as` which 'Appends this signature. If no primary signature is present, this signature is made the primary signature instead.'. Having an option to append the signature or overwrite would be really helpful.

**Comment by StefanKert** [comment]
Hi @amura11,

First of all I am very sorry for the delay. 

Can you provide an example on how this would look like? Is this signature a .crt file or is it just a text?
