### ISSUE TITLE
Task is not available after installation

### ISSUE THREAD

**Issue by InteXX** [StefanKert/azuredevops-codesigning-task#24]
I just installed this extension on my on-prem ADS 2019.1 instance, but it's not showing up in the list of available tasks for my pipeline.

Is there something more I need to do? There doesn't appear to be any special configuration needed under the extension management page.

**Comment by StefanKert** [comment]
Hi @InteXX ,

I am very sorry for the long time to respond. Is this still an issue?

**Comment by InteXX** [comment]
No problem. It's not as though there's a shortage of things to do around here ;-)

Yes, the problem still manifests.

The extension is installed:

![image](https://user-images.githubusercontent.com/10966749/101240276-c00ef000-369a-11eb-8237-2d868c7a874d.png)

...but no tasks are displayed for it:

![image](https://user-images.githubusercontent.com/10966749/101240291-d87f0a80-369a-11eb-9c00-12ea14b1e604.png)

You might have some ideas on how to get it working.

**Comment by StefanKert** [comment]
Hi there,

do you have access to your Azure DevOps admins panel, the url should be sth like this:

https://dev.azure.com/{ORGANIZATION}/_settings/extensions?tab=installed

In the past I´ve seen that the extension is still listed under "Requested" and needs to be accepted by an administrator.

**Comment by InteXX** [comment]
I reinstalled the extension from the marketplace and it's showing up now. Not sure what went wrong the first time.
