### ISSUE TITLE
PFX without a password?

### ISSUE THREAD

**Issue by spaddlewit** [StefanKert/azuredevops-codesigning-task#29]
Is it possible to use a PFX file without a password? On my local machine I typically sign with:

`signtool.exe sign /f mycert.pfx myApp.exe`

**Comment by StefanKert** [comment]
Even though the signtool itself works without password, I'd highly recommend to use passwords for PFX files in a Azure DevOps environment for various security reasons. For that reason CodeSigning will always require a password to be used.
