### ISSUE TITLE
Sign multiple files

### ISSUE THREAD

**Issue by schh** [StefanKert/azuredevops-codesigning-task#5]
I cant seem to sign multiple files at the same time like i can with regular signtool, is there some special syntax or do i have to add a new task for each file?

I tried using the same syntax as signtool with only spaces between each file.

Thanks

**Comment by StefanKert** [comment]
Hi @schh sorry for the delay. 

I am already testing the version of this tool internally. Since this involves a breaking change I need some more time to test but I expect a release until the end of March.

Cheers

**Comment by StefanKert** [comment]
As mentioned v2.0.0 has been released and comes along with support for wildcards! Hope you will like the new feature. If you have any further ideas please let me know!

**Comment by schh** [comment]
That is absolutely lovely. Thank you! ☺

Med vänliga hälsningar,

Robert Petersson
Utvecklare
[cid:image003.jpg@01D4C921.BA0C0280]
EDP
Järnvägsgatan 93
245 34  Staffanstorp
Reception 046-23 45 50
robert.petersson@edp.se
www.edp.se<http://www.edp.se/>

Från: Stefan Kert <notifications@github.com>
Skickat: den 29 mars 2019 16:41
Till: StefanKert/azuredevops-codesigning-task <azuredevops-codesigning-task@noreply.github.com>
Kopia: Robert Petersson <Robert.Petersson@edp.se>; Mention <mention@noreply.github.com>
Ämne: Re: [StefanKert/azuredevops-codesigning-task] Sign multiple files (#5)


As mentioned v2.0.0 has been released and comes along with support for wildcards! Hope you will like the new feature. If you have any further ideas please let me know!

**Comment by AndrewPlakhotnyi** [comment]
Would be great to make a "File(s) to sign" field "multiline". Now you can't set multiple files patterns. So, we need a task per pattern.
