### ISSUE TITLE
How to delete an uploaded .pfx certificate

### ISSUE THREAD

**Issue by timstspry1** [StefanKert/azuredevops-codesigning-task#54]
This is a question rather than an issue.  When the extension uploads the .pfx file to a Secure File in Azure DevOps, how is this certificate ever deleted if we no longer want to use this extension?

Thanks in advance!

Tim

**Comment by StefanKert** [comment]
Hi  @timstspry1,

so this extension doesn't upload things to the Secure Files. It just uses Secure Files that have been uploaded to Azure DevOps while signing and then cleans up all local versions of it.

If you want to delete Secure Files from Azure DevOps you can Navigate to Pipelines -> Library -> Secure Files and see a list of your pfx files. You can find more details in the official docs (https://learn.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops).

**Comment by timstspry1** [comment]
Thank you for your response!
